<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
      <PackageReference Include="xunit" Version="2.9.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ReportEngine\ReportEngine.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="DataFiles\programming-task-example-data-clean.log">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Include="DataFiles\programming-task-example-data.log">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
